Update lang-ca.json
pablozg/freeds pull request #62
Opened 2022-09-08 04:23 UTC by blacx0

Corregidos varios errores gramaticales y de estilo.

2022-09-08 11:28 UTC, svcabre requested changes
Hola,

Este string "Conexió WiFi Perdua" debería ser "Conexió WiFi Perduda"

2022-09-08 11:29 UTC, svcabre commented
Corrección error lang-ca.json

2022-09-08 11:30 UTC, svcabre commented
Error en la traducción

2022-10-04 10:37 UTC, pablozg commented
@svcabre Hola, prueba la última beta y dime si los errores persisten, ya que los ficheros de este repositorio son de la 1.0.7 rev 2, en caso de que sigan estando los errores te pasaría lo ficheros actuales para su corrección. Saludos.

2022-11-09 20:15 UTC, closed without merging